name: release
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches: 'main'
jobs:
    release:
        name: publish a new version
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: build package 📦
              run: npm run build
            - name: release
              run: npm run release
              env:
                  #TO DO - Not all three tokens *should* be needed
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  #NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
